import type { Metadata } from "next";
import localFont from "next/font/local";
import "@repo/ui/globals.css";
import Header from "@/components/common/layout/header";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/themes/theme-provider";
import { ModeToggle } from "@/components/ui/themeToggle";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Header />
                    
                    {children}
                    <Toaster position="top-right" expand closeButton />
                </ThemeProvider>
            </body>
        </html>
    );
}
