import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@repo/ui/globals.css";
import { Header } from "@/components/common/layout/header";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/themes/theme-provider";

const inter = Inter({
    subsets: ["latin", "vietnamese"],
    display: "swap",
    variable: "--font-inter",
    preload: true,
    fallback: ["system-ui", "Arial", "sans-serif"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${inter.variable} font-sans antialiased`}>
                <ThemeProvider>
                    <Header />

                    {children}
                    <Toaster position="top-right" expand closeButton />
                </ThemeProvider>
            </body>
        </html>
    );
}
